# -*- coding: utf-8 -*-
"""breast-cancer-deep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13GjUgll_a4jNlcJUtaQK67IwhDnVbieo
"""

from google.colab import drive
drive.mount("/content/drive/")

# Importing libraries
import pandas as pd
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# data containing path to Brain MRI and their corresponding mask
df = pd.read_csv('/content/drive/MyDrive/Breast cancer/Breast_cancer_data.csv')
#print(df.head())

dataset = df.to_numpy()

# split into input (X) and output (y) variables
X = dataset[:,0:5]
y = dataset[:,5]

# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(5,), activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=20)

# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)
# summarize the first 5 cases
for i in range(5):
	print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))